-- MySQL Script generated by MySQL Workbench
-- Mon Jul  8 19:20:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema contador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema contador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `contador` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `contador` ;

-- -----------------------------------------------------
-- Table `contador`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contador`.`cliente` (
  `codCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`codCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `contador`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contador`.`contrato` (
  `codContrato` INT NOT NULL AUTO_INCREMENT,
  `cliente` INT NULL DEFAULT NULL,
  `cantMeses` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codContrato`),
  INDEX `fkclientecontrato` (`cliente` ASC) VISIBLE,
  CONSTRAINT `fkclientecontrato`
    FOREIGN KEY (`cliente`)
    REFERENCES `contador`.`cliente` (`codCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `contador`.`tipoproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contador`.`tipoproducto` (
  `codtipo` INT NOT NULL AUTO_INCREMENT,
  `descripciontipo` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`codtipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `contador`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contador`.`productos` (
  `pn` VARCHAR(50) NOT NULL,
  `tipo` INT NOT NULL,
  `descripcion` VARCHAR(750) NOT NULL,
  `price` DOUBLE NOT NULL,
  `yield` VARCHAR(250) NULL DEFAULT NULL,
  `rmvp` VARCHAR(250) NULL DEFAULT NULL,
  `dutycycle` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`pn`),
  INDEX `fktipoproducto` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fktipoproducto`
    FOREIGN KEY (`tipo`)
    REFERENCES `contador`.`tipoproducto` (`codtipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `contador`.`facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contador`.`facturacion` (
  `facturaproducto` INT NOT NULL AUTO_INCREMENT,
  `contrato` INT NULL DEFAULT NULL,
  `producto` VARCHAR(50) NULL DEFAULT NULL,
  `preciofob` DOUBLE NULL DEFAULT NULL,
  `porcentajeflete` INT NULL DEFAULT NULL,
  `flete` DOUBLE NULL DEFAULT NULL,
  `margen` DOUBLE NULL DEFAULT NULL,
  `precioventa` DOUBLE NULL DEFAULT NULL,
  `tonermensual` INT NULL DEFAULT NULL,
  `toneranual` INT NULL DEFAULT NULL,
  `costoToner` DOUBLE NULL DEFAULT NULL,
  `facturacionToner` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`facturaproducto`),
  INDEX `fkcontrato` (`contrato` ASC) VISIBLE,
  INDEX `fkproducto` (`producto` ASC) VISIBLE,
  CONSTRAINT `fkcontrato`
    FOREIGN KEY (`contrato`)
    REFERENCES `contador`.`contrato` (`codContrato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkproducto`
    FOREIGN KEY (`producto`)
    REFERENCES `contador`.`productos` (`pn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `contador`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contador`.`usuarios` (
  `coduser` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(500) NULL DEFAULT NULL,
  `usuario` VARCHAR(500) NULL DEFAULT NULL,
  `contrasena` VARCHAR(750) NULL DEFAULT NULL,
  `correo` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`coduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
